# [START gae_quickstart_yaml]
runtime: nodejs14
# [END gae_quickstart_yaml]

# Application service name
service: default

# instance class
instance_class: F1

# Variables
env_variables:
  BUCKET_NAME: "example-gcs-bucket"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 15
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

#basic_scaling:
#  max_instances: 11
#  idle_timeout: 10m

#manual_scaling:
#  instances: 5