resources:
  - name: storage-bucket-aa-7451
    type: storage.v1.bucket
    properties:
      storageClass: STANDARD
  - name: my-instance-config-1
    type: compute.v1.instance
    properties:
      zone: us-central1-a
      machineType: https://www.googleapis.com/compute/v1/projects/gcp-done-stage1/zones/us-central1-a/machineTypes/f1-micro
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20150423
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/gcp-done-stage1/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
